name = "ProvabilityLogic"
version = "0.1.0"
defaultTargets = ["ProvabilityLogic"]

[[lean_lib]]
name = "ProvabilityLogic"

[[lean_lib]]
name = "ProvabilityLogicPlayground"

[[require]]
name = "Foundation"
git = "https://github.com/FormalizedFormalLogic/Foundation"
rev = "master"

[[require]]
name = "LeanTypst"
git = "https://github.com/SnO2WMaN/lean-typst.git"
rev = "main"
