module

public import ProvabilityLogic.LabelledGentzen.Basic
public import Mathlib.Combinatorics.Pigeonhole

@[expose]
public section

/-!
Looping sequents are provable (`[Neg14]` Lemma 5.2), and the pigeonhole
argument underlying the termination of proof search (`[Neg14]` Theorem 5.5):
along a chain of relational atoms longer than the number of available boxed
formulas, some boxed formula repeats at both ends of a subchain, so the
sequent is provable by Lemma 5.2.
-/

open LabelledGentzen

variable {α : Type u} [DecidableEq α]
         {R : Finset LabelRel} {Γ Δ : Finset (LabelledFormula α)}
         {x y z : Label} {A B : Formula α}


namespace LabelledGentzen.ProvableLabelledGentzen

/-- If `y` is reachable from `x` through a nonempty chain of relational atoms in `R`,
then the relational atom `(x, y)` can be discharged by `Trans`. -/
lemma of_transGen_insert (h : Relation.TransGen (λ a b => (a, b) ∈ R) x y)
  : ⊢ˡ (insert (x, y) R ⸴ Γ ⟹ˡ Δ) → ⊢ˡ (R ⸴ Γ ⟹ˡ Δ) := by
  induction h with
  | single hxy =>
    simp [Finset.insert_eq_self.mpr hxy];
  | @tail b c _ hbc ih =>
    intro π;
    apply ih;
    apply trans (x := x) (y := b) (z := c);
    apply wkRel π;
    grind;

/--
Chain form of the looping lemma: a looping sequent is provable. If there is a nonempty
chain of relational atoms from `x` to `y`, and the same boxed formula `□A`
occurs at `x` in the antecedent and at `y` in the succedent, the sequent is provable.
The single-edge case is `ProvableLabelledGentzen.loop` (`ProvabilityLogic.LabelledGentzen.Basic`).

- [Neg14, Lemma 5.2]
-/
lemma loopChain (h : Relation.TransGen (λ a b => (a, b) ∈ R) x y)
  (hx : (x ∶ □A) ∈ Γ := by grind) (hy : (y ∶ □A) ∈ Δ := by grind)
  : ⊢ˡ (R ⸴ Γ ⟹ˡ Δ) := by
  apply of_transGen_insert h;
  exact loop x y A;

/-- `ReflTransGen` variant of `loopChain`, additionally covering the degenerate case `x = y`. -/
lemma loopChain' (h : Relation.ReflTransGen (λ a b => (a, b) ∈ R) x y)
  (hx : (x ∶ □A) ∈ Γ := by grind) (hy : (y ∶ □A) ∈ Δ := by grind)
  : ⊢ˡ (R ⸴ Γ ⟹ˡ Δ) := by
  -- split on whether `x = y` (closed directly by `union`) or a genuine chain (delegate to `loopChain`)
  rcases Relation.reflTransGen_iff_eq_or_transGen.mp h with rfl | h;
  . exact union y (□A);
  . exact loopChain h hx hy;

omit [DecidableEq α] in
/-- A nonempty chain of relational atoms in `R` yields a `TransGen` step. -/
lemma transGen_of_isChain {l : List Label} (hl : l ≠ [])
  (hchain : (x :: l).IsChain (λ a b => (a, b) ∈ R))
  : Relation.TransGen (λ a b => (a, b) ∈ R) x (l.getLast hl) := by
  induction l generalizing x with
  | nil => grind
  | cons b l ih =>
    rcases List.isChain_cons_cons.mp hchain with ⟨hxb, hchain⟩;
    match l with
    | [] => exact Relation.TransGen.single hxb;
    | c :: l =>
      rw [List.getLast_cons (by grind)];
      exact Relation.TransGen.head hxb (ih (by grind) hchain);

/--
`List`-chain form of the looping lemma: `x R y₁, …, yₙ₋₁ R yₙ` with
`x ∶ □A` in the antecedent and `yₙ ∶ □A` in the succedent.

- [Neg14, Lemma 5.2]
-/
lemma loopChain_of_isChain {l : List Label} (hl : l ≠ [])
  (hchain : (x :: l).IsChain (λ a b => (a, b) ∈ R))
  (hx : (x ∶ □A) ∈ Γ := by grind) (hy : ((l.getLast hl) ∶ □A) ∈ Δ := by grind)
  : ⊢ˡ (R ⸴ Γ ⟹ˡ Δ) :=
  loopChain (transGen_of_isChain hl hchain) hx hy


section Pigeonhole

variable {n : ℕ} {xs : Fin (n + 1) → Label}

omit [DecidableEq α] in
/-- Any segment of a chain `xs 0 R xs 1 R … R xs n` yields a `ReflTransGen` step. -/
lemma reflTransGen_of_chain (hchain : ∀ i : Fin n, (xs i.castSucc, xs i.succ) ∈ R) (hab : a ≤ b)
  : Relation.ReflTransGen (λ u w => (u, w) ∈ R) (xs a) (xs b) := by
  induction b using Fin.induction with
  | zero =>
    grind;
  | succ i ih =>
    rcases eq_or_lt_of_le hab with rfl | hlt;
    . exact Relation.ReflTransGen.refl;
    . exact Relation.ReflTransGen.tail (ih (by grind)) (hchain i);

/--
Pigeonhole core of the termination argument: suppose that along a chain
`xs 0 R xs 1 R … R xs n` each edge `i` is generated by a boxed formula `□(f i)`,
occurring in the succedent at its source `xs i` and in the antecedent at its
target `xs (i + 1)`, with all `f i` drawn from a finite stock `X`.
If the chain has more edges than `X` has elements, then some boxed formula
repeats along the chain and the sequent is provable.

- [Neg14, Theorem 5.5]
-/
theorem provable_of_long_chain {X : Finset (Formula α)} (hX : X.card < n)
  (hchain : ∀ i : Fin n, (xs i.castSucc, xs i.succ) ∈ R)
  {f : Fin n → Formula α} (hf : ∀ i, f i ∈ X)
  (hant : ∀ i : Fin n, ((xs i.succ) ∶ □(f i)) ∈ Γ)
  (hsuc : ∀ i : Fin n, ((xs i.castSucc) ∶ □(f i)) ∈ Δ)
  : ⊢ˡ (R ⸴ Γ ⟹ˡ Δ) := by
  -- pigeonhole: more edges than elements of `X` forces two edges `i ≠ j` with `f i = f j`;
  -- whichever of `i.succ`, `j.succ` comes first, `loopChain'` closes the sequent via the repeat
  obtain ⟨i, -, j, -, hne, heq⟩ := Finset.exists_ne_map_eq_of_card_lt_of_maps_to
    (s := (Finset.univ : Finset (Fin n))) (t := X) (by simpa using hX) (λ i _ => hf i);
  wlog hij : i < j;
  . exact this (i := j) (j := i) ‹_› ‹_› ‹_› ‹_› ‹_› (by grind) (by grind) (by omega);
  apply loopChain' (A := f i) (reflTransGen_of_chain hchain ?_) (hant i) (by rw [heq]; exact hsuc j);
  grind;

end Pigeonhole

end LabelledGentzen.ProvableLabelledGentzen
