module

public import ProvabilityLogic.Kripke.RootExtension

@[expose]
public section

variable [Nonempty κ] {α}

namespace Model

namespace World

variable {M : Model κ α} {r x y : M.World}

/-- `x.IsInConeOf r` means that `x` belongs to the cone generated by `r`,
i.e. `x` is `r` itself or is reachable from `r`. -/
@[grind]
def IsInConeOf (x r : M.World) : Prop := x = r ∨ r ≺ x

@[simp, grind .]
lemma isInConeOf_self {r : M.World} : r.IsInConeOf r := by grind;

lemma isInConeOf_of_isInConeOf [IsTrans _ M.Rel] (h : x.IsInConeOf r) (Rxy : x ≺ y) : y.IsInConeOf r := by
  rcases h with (rfl | h);
  . right; assumption;
  . right; trans x <;> assumption;

@[grind]
def IsProperPredecessorOf (x r : M.World) : Prop := x ≠ r ∧ x ≺ r

end World


/-- The cone generated by `r` in `M`, i.e. the points that belong to the cone of `r`. -/
abbrev Cone (M : Model κ α) (r : M.World) := { x : M.World // x.IsInConeOf r }
infixl:60 "↾" => Cone

instance {M : Model κ α} : Nonempty (M↾r) := ⟨⟨r, by grind⟩⟩

instance {M : Model κ α} {r : M.World} [Finite M.World] : Finite (Cone M r) := Subtype.finite

@[grind]
def toRootedModel (M : Model κ α) (r : M.World) : RootedModel (M↾r) α where
  Rel' x y := M.Rel x y
  Val' x a := M.Val x a
  root := ⟨⟨r, by grind⟩, by grind⟩

namespace toRootedModel

variable {M : Model κ α} {r x : M.World} {A : Formula α}

instance [IsTrans _ M.Rel] : IsTrans _ (toRootedModel M r).Rel := by
  constructor;
  rintro ⟨x, rfl | Rrx⟩ ⟨y, rfl | Rry⟩ ⟨z, rfl | Rrz⟩ Rxy Ryz;
  case inl.inr.inl | inr.inl.inr | inr.inr.inl | inr.inr.inr =>
    simp_all only [Model.Rel, toRootedModel];
    trans y <;> assumption;
  all_goals
    simp_all only [Model.Rel, toRootedModel];

instance [Std.Irrefl M.Rel] : Std.Irrefl (toRootedModel M r).Rel := by
  constructor;
  rintro ⟨x, rfl | Rrx⟩ <;>
  . simp_all only [Model.Rel, toRootedModel];
    apply Std.Irrefl.irrefl;

instance [Finite M.World] : Finite (toRootedModel M r).World := inferInstance

instance [M.IsFiniteGL] : (toRootedModel M r).IsFiniteGL where


variable [IsTrans _ M.Rel]

open Model.World (Forces)

lemma forces_same_of_isInConeOf (hx : x.IsInConeOf r) : Forces (M := toRootedModel M r |>.toModel) ⟨x, hx⟩ A ↔ x ⊩ A := by
  induction A generalizing x with
  | atom a => simp [Forces, toRootedModel];
  | box A ihA =>
    constructor;
    . intro h y Rxy;
      apply ihA (Model.World.isInConeOf_of_isInConeOf hx Rxy) |>.mp;
      apply h;
      grind;
    . intro h y Rxy;
      apply ihA (Model.World.isInConeOf_of_isInConeOf hx Rxy) |>.mpr;
      apply h;
      grind;
  | _ => grind;

lemma forces_same_at_cone_point {x : (toRootedModel M r).World} : Forces x A ↔ Forces (M := M) x A :=
  forces_same_of_isInConeOf x.property

lemma forces_same_at_root : Forces (M := toRootedModel M r |>.toModel) ⟨r, by grind⟩ A ↔ Forces (M := M) r A :=
  forces_same_of_isInConeOf (by grind)

end toRootedModel


end Model

end
